name: example
description: "A Flutter example app for the flutter_ai_providers package."
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^0.6.7
  # flutter_ai_providers: ^0.1.0
  flutter_ai_providers:
    path: ../packages/flutter_ai_providers

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
