name: flutter_ai_providers
description: Community-contributed providers for the Flutter AI Toolkit.
version: 0.2.0
repository: https://github.com/davidmigloz/flutter_ai_community/tree/main/packages/flutter_ai_providers
issue_tracker: https://github.com/davidmigloz/flutter_ai_community/issues

topics:
  - ai
  - chat
  - llms

environment:
  sdk: ^3.5.0
  flutter: '>=3.27.0'

dependencies:
  llama_sdk: ^0.0.4
  anthropic_sdk_dart: ^0.2.0+1
  flutter:
    sdk: flutter
#  flutter_ai_toolkit: ^0.7.1
  flutter_ai_toolkit:
    path: ../../../flutter_ai_toolkit
  ollama_dart: ^0.2.2+1
#  openai_dart: ^0.4.5
  # 原码里面，返回数据格式和字节bots模型不兼容，使用定制版本
  # https://github.com/davidmigloz/langchain_dart/pull/777
  #  openai_dart: ^0.4.5
  openai_dart:
    git:
      url: git@github.com:baihua666/langchain_dart.git
      path: packages/openai_dart
  http: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
